'''
Класс нужен для избежания опечаток при написании названий команд.
Добавлять все новые команды сюда.
'''
class bot_command:
    add = 'add'
    all = 'all'
    chatid = 'chatid'
    delete = 'delete'
    get = 'get'
    help = 'help'
    linal = 'linal'
    mark_formulas = 'mark_formulas'
    marks = 'marks'
    oakbus = 'oakbus'
    recordings = 'recordings'
    start = 'start'
    subs = 'subs'
    subscribe = 'subscribe'
    today = 'today'
    unsubscribe = 'unsubscribe'
    userid = 'userid'
    wiki = 'wiki'
